### ISSUE TITLE
Fixing x-default in /guides

### ISSUE THREAD

**Issue by rbatista191** [tramitit/tramitit.github.io#3]
Long thread, let me see if I can summarize it:

- AHREFs identifies that the `rel=alternate` tags are not placed correctly
- In the Hugo foruns, [this guy solved the issue](https://discourse.gohugo.io/t/setting-the-x-default-in-the-istranslated-loop-as-i-want/44087/2)
- However, when I implemented it with a partial in `partials/head.html` the old `rel=alternate` are still showing up (probably triggered by a partial that I cannot access):

![Screenshot 2024-06-11 at 12 46 54](https://github.com/tramitit/tramitit.github.io/assets/138892976/987173b8-cb60-46b7-adf7-dad494be1c1a)

@awennersteen can you help me on this?

Here is a good website to test the schema: https://technicalseo.com/tools/hreflang/

This is the official guide from Hugo for localization: https://gohugo.io/content-management/multilingual/

**Comment by awennersteen** [comment]
I think you had it correct, I made some changes whilst understanding but I think it was correct already:
![image](https://github.com/tramitit/tramitit.github.io/assets/26585675/a423987a-b7c9-42cc-b0f4-2ea208c54e01)


However I noted that if you check tramitit.com without pointing to a post it doesn't pass. 
I'll check if we can add something there

Edit:
It appears that 
https://tramitit.com doesnt pass but
https://tramitit.com/en does, 
I don't know if that is correct or not?

It also complains about duplicate references and such, I don't fully understand what these tags are for how they should be set so let me have a look

**Comment by rbatista191** [comment]
> Edit: It appears that https://tramitit.com doesnt pass but https://tramitit.com/en does, I don't know if that is correct or not?
> 
> It also complains about duplicate references and such, I don't fully understand what these tags are for how they should be set so let me have a look

@awennersteen the problem is the duplicate references indeed. I have an [ongoing thread](https://discourse.gohugo.io/t/question-about-hreflang-attribute/50240/4) with Hugo's support, I also need to test these tags to see what matches what AHREF wants. But for the time being, I need to be able to remove the default ones.

See if my ticket to Hugo's support is clear, we can also have a call.

**Comment by awennersteen** [comment]
gotcha, now I understand the problem.
Is the last reply by the guy the answer, looks like it to me, I'll try

**Comment by rbatista191** [comment]
> gotcha, now I understand the problem. Is the last reply by the guy the answer, looks like it to me, I'll try

Doesn't look like it, it still generates several `rel=alternate`:
<img width="635" alt="Screenshot 2024-06-11 at 17 51 34" src="https://github.com/tramitit/tramitit.github.io/assets/138892976/57d95b6c-702d-4167-bf40-81b3ee54ee2e">

**Comment by awennersteen** [comment]
Yeah, so that fixed the case for english.

**Comment by awennersteen** [comment]
I still don't understand what's wrong with the alternate ones tbh

Edit:
I now understand, I think I know how to debug

**Comment by awennersteen** [comment]
https://github.com/gethugothemes/hugo-modules/blob/3af75203b2efa73a0d98a29d4ca7beb1f7ec563d/seo-tools/basic-seo/layouts/partials/basic-seo.html#L31C1-L38C10

The same piece of code is in a base hugo module we use

**Comment by rbatista191** [comment]
Issues fixed using the [ongoing thread](https://discourse.gohugo.io/t/question-about-hreflang-attribute/50240/4) information. Thanks @awennersteen !
